// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240605071948_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "Operations"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "Development"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Sales"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "HR"
                        });
                });

            modelBuilder.Entity("DataAccess.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 640, DateTimeKind.Local).AddTicks(7426),
                            DeptId = 1,
                            Name = "Sal",
                            Salary = 7000
                        },
                        new
                        {
                            Id = 102,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4945),
                            DeptId = 1,
                            Name = "Will",
                            Salary = 8000
                        },
                        new
                        {
                            Id = 103,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4979),
                            DeptId = 2,
                            Name = "John",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 104,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4983),
                            DeptId = 2,
                            Name = "Julie",
                            Salary = 20000
                        },
                        new
                        {
                            Id = 105,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4987),
                            DeptId = 2,
                            Name = "Sam",
                            Salary = 8000
                        },
                        new
                        {
                            Id = 106,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4995),
                            DeptId = 3,
                            Name = "Jude",
                            Salary = 20000
                        },
                        new
                        {
                            Id = 107,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(4998),
                            DeptId = 3,
                            Name = "Jen",
                            Salary = 15000
                        },
                        new
                        {
                            Id = 108,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(5001),
                            DeptId = 4,
                            Name = "Ram",
                            Salary = 11000
                        },
                        new
                        {
                            Id = 109,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(5004),
                            DeptId = 4,
                            Name = "Violet",
                            Salary = 12000
                        },
                        new
                        {
                            Id = 110,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(5008),
                            DeptId = 2,
                            Name = "Andy",
                            Salary = 30000
                        },
                        new
                        {
                            Id = 111,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(5011),
                            DeptId = 1,
                            Name = "Molly",
                            Salary = 16000
                        },
                        new
                        {
                            Id = 112,
                            DateCreated = new DateTime(2024, 6, 5, 3, 19, 47, 643, DateTimeKind.Local).AddTicks(5014),
                            DeptId = 2,
                            Name = "Vincent",
                            Salary = 6000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
